---
title: "Coin flipping - simplified"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{coin-example}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE
)

options(rmarkdown.html_vignette.check_title = FALSE)
```


```{r setup}
library(treepplr)
library(dplyr)
library(ggplot2)
```

Get path to the JSON file that contains the data for the coin model.

```{r}
data <- tp_data(data_input = "coin")
data

jsonlite::fromJSON(data)
```

Generate sampler for method SMC bpf

```{r}
coin_bpf_sampler <- tp_compile(model = "coin", method = "smc-bpf", particles = 5000)
coin_bpf_sampler
```

Run treeppl

```{r, eval=FALSE}
output_list <- tp_run(coin_bpf_sampler, data, n_runs = 2, n_processes = 2)
str(output_list, max.level = 2)
```

```{r, echo=FALSE, eval=FALSE}
# save RDS file
saveRDS(output_list, "vignettes/rdata/coin/output_coin_simple.rds")
```

```{r, echo=FALSE}
output_list <- readRDS("rdata/coin/output_coin_simple.rds")
```


```{r}
output <- tp_parse_smc(output_list)

tp_smc_convergence(output)
```

It seems that our run provides a quite accurate estimate of the posterior distribution,
as the variance is much smaller than 1.0.

It is also easy to plot the sampled values.

```{r, fig.height=5, fig.width=5}
ggplot2::ggplot(output, ggplot2::aes(samples, weight = norm_weight)) +
  ggplot2::geom_histogram(ggplot2::aes(y = ggplot2::after_stat(density)),
                 col = "white", fill = "grey60", binwidth=0.01) +
  ggplot2::geom_density(aes(col = as.factor(sweep)), linewidth = 1) +
  ggplot2::theme_bw()

```



